language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli@0.1.13 karma-cli@0.0.4
  - gem install sass
script: grunt travis
sudo: false
cache:
  directories:
    - node_modules
